In [39]:
import numpy as np
import pandas as pd

In [40]:
df=pd.read_csv('global_heat_index.csv')
df

,Year,Month,Day,Hour,Dew Point,Temperature,Pressure,Relative Humidity,Wind Direction,Wind Speed,Solar Radiation (GHI)
0,2011,1,1,0,8,13.522659,986.761841,72.295858,37.288387,3.011042,0
1,2011,1,1,1,8,12.835814,986.441406,75.376186,37.686718,3.091243,0
2,2011,1,1,2,8,12.198058,985.736511,78.405198,35.053905,3.007649,0
3,2011,1,1,3,8,11.583500,985.525696,81.042980,30.135216,2.926715,0
4,2011,1,1,4,8,11.029578,985.661926,82.548508,24.402969,2.915177,0
...,...,...,...,...,...,...,...,...,...,...,...
17515,2012,12,31,19,-6,14.702595,984.779114,22.647353,54.538628,3.383211,0
17516,2012,12,31,20,-6,13.823766,985.189148,23.993252,61.517830,3.519155,0
17517,2012,12,31,21,-6,12.951590,984.829224,25.759637,65.096191,3.518434,0
17518,2012,12,31,22,-5,12.138259,984.735046,27.901296,66.668427,3.400819,0
17519,2012,12,31,23,-5,11.420336,984.559753,29.884402,67.321007,3.246163,0

In [41]:
df.isnull().sum()

Year                     0
Month                    0
Day                      0
Hour                     0
Dew Point                0
Temperature              0
Pressure                 0
Relative Humidity        0
Wind Direction           0
Wind Speed               0
Solar Radiation (GHI)    0
dtype: int64

In [42]:
df1=df[df['Hour']<6]
df2=df[df['Hour']>18]

In [43]:
df=df.drop(df1.index,axis=0)
df=df.drop(df2.index,axis=0)

In [44]:
df.head(20)

,Year,Month,Day,Hour,Dew Point,Temperature,Pressure,Relative Humidity,Wind Direction,Wind Speed,Solar Radiation (GHI)
6,2011,1,1,6,2,7.806705,986.249146,67.093181,95.835983,1.815175,0
7,2011,1,1,7,2,9.036408,987.038940,64.035483,105.198181,1.615310,0
8,2011,1,1,8,3,12.158280,987.897400,55.105656,113.317665,1.439088,159
9,2011,1,1,9,3,14.965301,988.211914,47.166938,117.327606,1.063374,363
10,2011,1,1,10,3,18.956082,988.054504,36.747087,72.488327,0.545695,533
11,2011,1,1,11,2,21.354047,987.463867,29.157015,12.976929,0.980117,649
12,2011,1,1,12,2,22.161257,986.386169,27.593071,4.777779,1.411915,698
13,2011,1,1,13,2,22.256216,985.736511,27.274695,5.355347,1.747909,675
14,2011,1,1,14,2,21.725884,985.521545,27.819289,6.877182,2.005287,582
15,2011,1,1,15,2,20.507269,985.279663,30.023284,10.448921,2.206879,430
16,2011,1,1,16,5,18.190106,985.668091,43.187772,16.174072,2.304465,232
17,2011,1,1,17,5,15.665956,986.169922,49.346720,23.485420,2.516871,25
18,2011,1,1,18,4,14.728780,986.536682,50.818219,30.906128,2.666706,0
30,2011,1,2,6,3,7.624648,985.979248,74.198056,88.591377,1.047463,0
31,2011,1,2,7,5,8.805419,986.882507,77.175647,91.900917,0.894640,0
32,2011,1,2,8,2,11.871008,987.408203,51.505139,104.388344,0.976671,158
33,2011,1,2,9,4,14.709809,988.044189,49.772821,113.155838,0.960179,358
34,2011,1,2,10,4,18.741945,987.881409,38.852614,91.461777,0.676744,537
35,2011,1,2,11,3,21.265397,987.003174,31.481747,57.882504,0.707640,636
36,2011,1,2,12,3,22.211463,985.854370,29.990750,51.598942,0.853240,684

In [45]:
x = df.iloc[:, 0:10]
y = df.iloc[:, -1]

In [46]:
x.shape

(9490, 10)

In [47]:
y.shape

(9490,)

In [48]:
from sklearn.preprocessing import MinMaxScaler
x = pd.DataFrame(MinMaxScaler().fit(x).transform(x))

In [49]:
x

,0,1,2,3,4,5,6,7,8,9
0,0.0,0.0,0.0,0.000000,0.545455,0.058249,0.751583,0.667870,0.266273,0.245979
1,0.0,0.0,0.0,0.083333,0.545455,0.084360,0.779201,0.637009,0.292294,0.218438
2,0.0,0.0,0.0,0.166667,0.563636,0.150650,0.809220,0.546880,0.314862,0.194155
3,0.0,0.0,0.0,0.250000,0.563636,0.210254,0.820218,0.466754,0.326007,0.142382
4,0.0,0.0,0.0,0.333333,0.563636,0.294994,0.814713,0.361586,0.201380,0.071046
...,...,...,...,...,...,...,...,...,...,...
9485,1.0,1.0,1.0,0.666667,0.363636,0.406748,0.661102,0.095294,0.015946,0.249092
9486,1.0,1.0,1.0,0.750000,0.345455,0.374816,0.654829,0.104142,0.023550,0.262867
9487,1.0,1.0,1.0,0.833333,0.381818,0.316482,0.661057,0.141926,0.048566,0.297785
9488,1.0,1.0,1.0,0.916667,0.418182,0.247227,0.664845,0.208352,0.081641,0.364545
9489,1.0,1.0,1.0,1.000000,0.400000,0.223853,0.681064,0.212611,0.118426,0.424565

In [50]:
col = ['Year', 'Month', 'Day', 'Hour', 'Dew Point', 'Temperature', 'Pressure',
       'Relative Humidity', 'Wind Direction', 'Wind Speed',]

## CORRELATION

In [51]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(x,y)

MemoryError: could not allocate 130023424 bytes

## VISUALIZATION

In [52]:
# Data Feature scores 

feature_importances = pd.Series(model.feature_importances_, index = col)
feature_importances

SyntaxError: invalid syntax (<ipython-input-52-5748b8955d97>, line 2)

In [ ]:
feature_importances.nlargest(10).plot(kind='bar')
plt.show()